CREATE TABLESPACE TS_SOLOWEB DATAFILE 'E:\oracle\oradata\orcl\SOLOWEB.DBF' SIZE 100M AUTOEXTEND ON;

CREATE USER "SISMASTER"
IDENTIFIED BY "SIS!MASTER"
DEFAULT TABLESPACE TS_SOLOWEB
TEMPORARY TABLESPACE TEMP;

GRANT DBA TO SISMASTER;

COMMIT;